version: '3'

services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile.dev
    volumes:
      - ./src/api:/go/src/api
      - vendor:/go/src/api/vendor
    ports:
      - 8000:8000
    tty:
      true

volumes:
  vendor:
