FROM golang:1.11-alpine

COPY . /go/src/api/

WORKDIR /go/src/api/

# Install Dep and Gin
RUN apk update \
  && apk add --no-cache git \
  && go get -u github.com/codegangsta/gin \
  && go get -u github.com/golang/dep/cmd/dep \
  && dep ensure

CMD gin -i run