FROM golang:1.11-alpine

COPY src/api /go/src/api

WORKDIR /go/src/api

RUN apk update \
  && apk add --no-cache git \
  && go get -u github.com/codegangsta/gin \
  && go get -u github.com/golang/dep/cmd/dep

RUN dep ensure

CMD gin -i run